### ISSUE TITLE
Move this to Confluence?

### ISSUE THREAD

**Issue by darcyclarke** [telusdigital/reference-architecture#12]
The My Accounts team just finished their hackathon last week and one group happened to focus on inefficiencies in our process. What they found (after polling the entire team) was that documentation discovery was the biggest pain across the board. 

Standardizing and centralizing docs in one place is, I think, the ideal. There's a space already defined for this content so hopefully it wouldn't be too much work to transfer everything there. https://telusdigital.atlassian.net/wiki/display/TOS/Reference+Architecture

**Comment by ahmadnassri** [comment]
@darcyclarke we've had this conversation prior, so I'll document it here for future prosperity:

- All technical documentation live in github already (in individual project / product repos), the architecture should follow suit
- Confluence is used for product, and process documentation for internal teams
- we want to leverage github mechanisms here (Pull Request, Review, issues, etc ...)
- the goal for this repo is to eventually become public! _Confluence will not be a good fit for that_
