### ISSUE TITLE
service virtualization of a SOAP dependency

### ISSUE THREAD

**Issue by pawankeer** [telusdigital/reference-architecture#92]
What 

To mock BTO SOAP service

Why

PT is unstable as several teams use it and break it occasionally.
Our consumer/integration/e2e tests run on the PT env it break our pipeline

Why

Our tests should run against mock. The mock should validate the schema rather than the data with the PT service.

Who

@pawan & @skalfyfan to spike some tools out there

**Comment by skalfyfan** [comment]
@pawankeer I think we want to put this here instead:
https://github.com/telusdigital/architecture-forum/issues

**Comment by pawankeer** [comment]
moved to https://github.com/telusdigital/architecture-forum/issues
